name: Docker build on push
env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
    push:
        branches:
            - master

jobs:
        build:
                runs-on: ubuntu-20.04
                name: Build and push all the stuff defined in this repo
                steps:
                        - name: Checkout repo
                          uses: actions/checkout@v2

                        - name: Set env variables
                          run: |
                                  echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
                                  echo "SHORTSHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
                                  echo "DOCKER_HUB_REPO=tor" >> $GITHUB_ENV

                        - name: Show set env variables
                          run: |
                                  printf "    BRANCH: %s\n"  "$BRANCH"
                                  printf "    SHORTSHA: %s\n"  "$SHORTSHA"
                                  printf "    REPO: %s\n" "$GITHUB_REPOSITORY"
                                  printf "    COMMIT ID: %s\n" "$GITHUB_SHA"
                                  printf "    DOCKER REPO: %s\n" "$DOCKER_HUB_REPO"
                                  printf "    GITHUB_ACTOR: %s\n" "$GITHUB_ACTOR"
                                  printf "    GITHUB_REPOSITORY: %s\n" "$GITHUB_REPOSITORY"

                        - name: Login to GitHub Container Registry
                          uses: docker/login-action@v1 
                          with:
                            registry: ghcr.io
                            username: ${{ github.repository_owner }}
                            password: ${{ secrets.GITHUB_TOKEN }}

                        - name: Setup Docker buildx action
                          uses: docker/setup-buildx-action@v1

                        - name: Show available Docker buildx platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}

                        - name: Cache Docker layers
                          uses: actions/cache@v2
                          id: cache
                          with:
                              path: /tmp/.buildx-cache
                              key: ${{ runner.os }}-buildx-${{ github.sha }}
                              restore-keys: |
                                  ${{ runner.os }}-buildx-

                        - name: Build against master
                          run: |
                                  docker buildx build \
                                  --cache-from "type=local,src=/tmp/.buildx-cache" \
                                  --cache-to "type=local,dest=/tmp/.buildx-cache" \
                                  --platform linux/amd64,linux/arm64 \
                                  --tag ghcr.io/${{ github.repository_owner }}/tor:master-$SHORTSHA \
                                  --output "type=registry" .
